sudo: required
dist: trusty

language: bash

services:
- docker

env:
- TEST=nginx
- TEST=mysql
- TEST=php
- TEST=wp

before_install:
- curl -L https://goss.rocks/install | sudo sh

script:
- cd build/$TEST && make
