version: '3.5'

volumes:
  www:
  dbd:
  web:
  php:

services:
  web:
    build: build/nginx
    image: devedotus/deve:web
    ports:
      - '8080:8080'
      - '4433:4433'
    volumes:
      - web:/etx/nginx
      - www:/var/www
    restart: unless-stopped

  php:
    build: build/php
    image: devedotus/deve:php
    depends_on:
      - mysql
    volumes:
      - www:/var/www
    restart: unless-stopped

  mysql:
    build: build/mysql
    image: devedotus/deve:mysql
    volumes:
      - dbd:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  wp:
    build: build/wp
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ../cli:/var/cli
      - www:/var/www
    restart: "no"
    environment:
      DEVE_DOMAIN: ${DEVE_DOMAIN}
      DEVE_DATABASE: ${DEVE_DATABASE}
      DEVE_DATABASE_PASSWORD: ${DEVE_DATABASE_PASSWORD}
      DEVE_USER: ${DEVE_USER}
      DEVE_PASSWORD: ${DEVE_PASSWORD}
      DEVE_EMAIL: ${DEVE_EMAIL}
      DEVE_TITLE: ${DEVE_TITLE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
