version: "3.5"

volumes:
  www:

services:
  web:
    build: build/nginx
    image: devedotus/deve:web
    ports:
      - "80:80"
    volumes:
      - www:/var/www/html:ro
    restart: unless-stopped

  php:
    image: wordpress:fpm-alpine
    depends_on:
      - mysql
    volumes:
      - www:/var/www/html:rw
    restart: unless-stopped
    environment:
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}

  mysql:
    image: yobasystems/alpine-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
