version: '3'
volumes:
  www:
    name: 'deve_www'
  web:
    name: 'deve_web'
  php:
    name: 'deve_php'
  ssl:
    name: 'deve_ssl'
  tmp:
    name: 'deve_tmp'
  dba:
    name: 'deve_dba'

services:
  ############
  # SERVICES
  ############
  web:
    container_name: 'deve_web'
    build: build/web
    image: nginx:alpine
    user: www-data
    volumes:
      - www:/var/www
      - ssl:/etc/letsencrypt
      - web:/etc/nginx
      - tmp:/tmp
    ports:
      - '80:80'
      - '443:443'
    restart: always
  php:
    container_name: 'deve_php'
    build: build/php
    image: php:fpm-alpine
    user: www-data
    volumes:
      - php:/usr/local/etc
      - www:/var/www
      - tmp:/tmp
    restart: always
  dba:
    container_name: 'deve_dba'
    #build: build/dba
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - dba:/var/lib/mysql
    restart: always
  #backup:
  #  build: build/backup
  #  image: jsmitsnl/docker-restic:latest
  #  volumes:
  #    - www:/data/www
  #    - web:/data/web
  #    - php:/data/php
  #    - ssl:/data/ssl
  #  environment:
  #    - RESTIC_CLEANUP_OPTIONS="--prune"
  #    - RESTIC_BACKUP_OPTIONS="--exclude=/data/wp-content/cache/*"
  #    - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}
  #    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #    - RESTIC_PASSWORD=${RESTIC_PASSWORD}
  #  restart: always

  ############
  # Logger
  ############
  #log:
  #  build: build/log
  #  image: gliderlabs/logspout
  #  volumes:
  #    - '/var/run/docker.sock:/var/run/docker.sock'
  #  command: "syslog+tls://${PAPERTRAIL_URL}"
  #  restart: always

  #########
  # Tools
  #########
  cli:
    container_name: 'deve_cli'
    build: build/cli
    image: wordpress:cli
    user: www-data
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-db}
      WORDPRESS_DB_USER: ${MYSQL_USER:-user}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - www:/var/www
      - web:/etc/nginx
      - php:/usr/local/etc
      - /home/tstachl/cli:/var/cli
  
