version: '3.5'

volumes:
  www:

services:
  web:
    build: build/nginx
    image: devedotus/deve:web
    volumes:
      - www:/var/www/wordpress
    restart: unless-stopped

  php:
    image: wordpress:fpm-alpine
    depends_on:
      - mysql
    volumes:
      - www:/var/www/wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}

  mysql:
    image: yobasystems/alpine-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
