version: '3.5'

volumes:
  www:
  dbd:

services:
  web:
    build: build/nginx
    image: devedotus/deve:web
    ports:
      - '8080:8080'
      - '4433:4433'
    volumes:
      - www:/var/www/wordpress:ro
      - ./config/wordpress.conf:/etc/nginx/default.conf:ro
    restart: unless-stopped

  php:
    build: build/php
    image: devedotus/deve:php
    depends_on:
      - mysql
    volumes:
      - www:/var/www/wordpress:rw
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}

  mysql:
    build: build/mysql
    image: devedotus/deve:mysql
    volumes:
      - dbd:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
